-- stg_labor__daily: staging view over raw.labor_daily (1:1, cast + normalize, no business logic)
-- Cleaning checklist:
--   - types; normalize role casing/whitespace
--
-- Status: STUB. The query body here is written by hand by the repo owner
-- (ownership rule in the README's Decisions section). Scaffolding only
-- carries the spec; committing generated SQL here would defeat the point.
