-- marts.fact_ticket_line
-- Grain: one deduplicated POS ticket line; net-sales rule applied once here; PK doubles as the dedup test; daypart_id and is_brunch materialized here
-- Owner-written DDL + INSERT/SELECT from staging views. Types, keys and
-- CHECK constraints are part of the interview surface and are hand-written.
--
-- Status: STUB. The query body here is written by hand by the repo owner
-- (ownership rule in the README's Decisions section). Scaffolding only
-- carries the spec; committing generated SQL here would defeat the point.
